### ISSUE TITLE
我想问一下博主是通过什么方法能在Service中收到后台的推送呢?

### ISSUE THREAD

**Issue by Dawnton** [xingda920813/XDUpdate#1]
是用的RxJava实现的吗?具体太看懂,希望解释一下,谢谢了

**Comment by xingda920813** [comment]
抱歉没太看懂你的问题？
1.这个库需要将JSON上传到一个可以被直接访问到的地址（即支持外链），然后调用XdUpdateAgent.update(Activity activity)时，会下载这个JSON，获取里面的版本信息，然后判断是否有更新，显示通知还是不显示。这个过程只是简单的文件下载，并没有集成推送。
2.XdUpdateService 没有接收推送的功能，如果要做更新的推送提示，可以使用一些第三方的推送服务（LeanCloud，友盟，MiPush等）。
3.Service 里显示的通知用于提示下载进度，这里只是调用 NotificationManager 显示一条通知。
(1).通过 Response.body().byteStream() 拿到 Response 对应的 InputStream;
(2).发送 TYPE_DOWNLOADING 类型的消息给 Service 内的 Handler；

> handler.sendEmptyMessage(TYPE_DOWNLOADING);

(3).发送消息后开始下载，下载过程中会不断更新length的值（length = length + hasRead），这个值标志着当前已经下载了多少字节；
(4).Handler收到消息后会去读取当前的length值，然后调用 NotificationManager 把下载进度更新到通知上；

> manager.notify(2,builder.setContentText(XdUpdateUtils.formatToMegaBytes(length) + "M/" + XdUpdateUtils.formatToMegaBytes(fileLength) + "M").setProgress(fileLength, length, false).build());

(5).500ms 后发一条同样类型的消息(TYPE_DOWNLOADING)，这个消息收到后重复步骤(4)，但此时length的值已经被下载过程的循环更新过，通知上显示的就是当前的进度。

> sendEmptyMessageDelayed(TYPE_DOWNLOADING, 500);

更新过程：

> while ((hasRead = is.read(buffer)) > 0) {
>                                 if (interrupted) return;
>                                 fos.write(buffer, 0, hasRead);
>                                 length = length + hasRead;
>                             }

(6).如果已经跳出了上面代码中的循环，说明已经下载完成，发送TYPE_FINISHED类型的消息取消掉通知。

**Comment by Dawnton** [comment]
哦,我的问题是接收推送功能的实现(楼上第2个回答),不过还是谢谢博主这么耐心的回答,哈哈

**Comment by xingda920813** [comment]
现在稍微灵活一点了，XdUpdateAgent.Builder现在有了一个setUpdateBean方法，通过这个方法构建的XdUpdateAgent实例，可以不使用JSON文件，而是接收一个XdUpdateBean。

可使用第三方推送服务的自定义消息/透传功能，接收到服务端推送过来的JSON(String)后，解析成一个XdUpdateBean，传入上述方法，即可使用推送带过来的JSON进行更新提示。

注意不是普通消息，这样会直接在通知栏上显示内容，不会进到自定义的代码处理块。
