### ISSUE TITLE
每次需要手动清除缓存才能看到更新

### ISSUE THREAD

**Issue by dangfan** [xingda920813/XDUpdate#3]
我的json文件放在七牛，已经将文件设置为max-age=30。但不能自动弹出更新，请问这是bug么？

**Comment by dangfan** [comment]
我调试了一下，发现是 `getMd5ByFile` 这个方法的回调进入了 `onSubscribe` 里，而不是 `onNext`。

**Comment by xingda920813** [comment]
我修复在了 1.9.1 版本, 试一下.
